// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as View$ReactNative from "reason-react-native/src/components/View.bs.js";
import * as ReactNativeReanimated from "react-native-reanimated";

var make = ReactNativeReanimated.default.createAnimatedComponent(ReactNative.View);

var View = View$ReactNative.View;

export {
  View ,
  make ,
  
}
/* make Not a pure module */
